function selectChange() {
    const day = document.getElementById("day").value;
    let output = "";
    switch (day) {
        case '0':
            output = "<h3>今天所有素材都可刷</h3>";
            break;
        case '1':
        case '4':
            output = '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Freedom.png" alt="Mondstadt Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">忘卻之峽(蒙德)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="安柏" src="AvatarIcon/UI_AvatarIcon_Ambor.png" alt="安柏"  style="background-color:#745a95;">'
                + '<img loading="eager" title="芭芭拉" src="AvatarIcon/UI_AvatarIcon_Barbara.png" alt="芭芭拉" style="background-color:#745a95;">'
                + '<img loading="eager" title="迪奧娜" src="AvatarIcon/UI_AvatarIcon_Diona.png" alt="迪奧娜" style="background-color:#745a95;">'
                + '<img loading="eager" title="可莉" src="AvatarIcon/UI_AvatarIcon_Klee.png" alt="可莉" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(風)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(風)" style="background-color:#745a95;">'
                + '<img loading="eager" title="女旅行者(風)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(風)" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(岩)" style="background-color:#745a95;">'
                + '<img loading="eager" title="女旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(岩)" style="background-color:#745a95;">'
                + '<img loading="eager" title="砂糖" src="AvatarIcon/UI_AvatarIcon_Sucrose.png" alt="砂糖" style="background-color:#745a95;">'
                + '<img loading="eager" title="達達利亞" src="AvatarIcon/UI_AvatarIcon_Tartaglia.png" alt="達達利亞" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/mondstadt_mon4.png" alt="Mondstadt Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">塞西莉亞苗圃(蒙德)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="鴉羽弓" src="EquipIcon/UI_EquipIcon_Bow_Crowfeather.png" alt="鴉羽弓"  style="background-color:#53799e;">'
                + '<img loading="eager" title="幽夜華爾滋" src="EquipIcon/UI_EquipIcon_Bow_Nachtblind.png" alt="幽夜華爾滋" style="background-color:#745a95;">'
                + '<img loading="eager" title="絕弦" src="EquipIcon/UI_EquipIcon_Bow_Troupe.png" alt="絕弦" style="background-color:#745a95;">'
                + '<img loading="eager" title="蒼翠獵弓" src="EquipIcon/UI_EquipIcon_Bow_Viridescent.png" alt="蒼翠獵弓" style="background-color:#745a95;">'
                + '<img loading="eager" title="魔導緒論" src="EquipIcon/UI_EquipIcon_Catalyst_Intro.png" alt="魔導緒論" style="background-color:#53799e;">'
                + '<img loading="eager" title="宗室祕法錄" src="EquipIcon/UI_EquipIcon_Catalyst_Theocrat.png" alt="宗室祕法錄" style="background-color:#745a95;">'
                + '<img loading="eager" title="西風秘典" src="EquipIcon/UI_EquipIcon_Catalyst_Zephyrus.png" alt=西風秘典"" style="background-color:#745a95;">'
                + '<img loading="eager" title="鐵影闊劍" src="EquipIcon/UI_EquipIcon_Claymore_Glaive.png" alt="鐵影闊劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="雪葬的星銀" src="EquipIcon/UI_EquipIcon_Claymore_Dragonfell.png" alt="雪葬的星銀" style="background-color:#745a95;">'
                + '<img loading="eager" title="鐘劍" src="EquipIcon/UI_EquipIcon_Claymore_Troupe.png" alt="鐘劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="松籟響起之時" src="EquipIcon/UI_EquipIcon_Claymore_Widsith.png" alt="松籟響起之時" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="冷刃" src="EquipIcon/UI_EquipIcon_Sword_Steel.png" alt="冷刃" style="background-color:#53799e;">'
                + '<img loading="eager" title="狼牙" src="EquipIcon/UI_EquipIcon_Sword_Boreas.png" alt="狼牙" style="background-color:#745a95;">'
                + '<img loading="eager" title="辰砂之紡錘" src="EquipIcon/UI_EquipIcon_Sword_Opus.png" alt="辰砂之紡錘" style="background-color:#745a95;">'
                + '<img loading="eager" title="暗巷閃光" src="EquipIcon/UI_EquipIcon_Sword_Outlaw.png" alt="暗巷閃光" style="background-color:#745a95;">'
                + '<img loading="eager" title="宗室長劍" src="EquipIcon/UI_EquipIcon_Sword_Theocrat.png" alt="宗室長劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="西風劍" src="EquipIcon/UI_EquipIcon_Sword_Zephyrus.png" alt="西風劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="風鷹劍" src="EquipIcon/UI_EquipIcon_Sword_Falcon.png" alt="風鷹劍" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Prosperity.png" alt="Liyue Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">太山府(璃月)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="刻晴" src="AvatarIcon/UI_AvatarIcon_Keqing.png" alt="刻晴" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="凝光" src="AvatarIcon/UI_AvatarIcon_Ningguang.png" alt="凝光" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="申鶴" src="AvatarIcon/UI_AvatarIcon_Shenhe.png" alt="申鶴" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="七七" src="AvatarIcon/UI_AvatarIcon_Qiqi.png" alt="七七" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="魈" src="AvatarIcon/UI_AvatarIcon_Xiao.png" alt="魈" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="夜蘭" src="AvatarIcon/UI_AvatarIcon_Yelan.png" alt="夜蘭" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/liyue_mon4.png" alt="Liyue Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">震雷連山密宮(璃月)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="彈弓" src="EquipIcon/UI_EquipIcon_Bow_Sling.png" alt="彈弓" style="background-color:#53799e;">'
                + '<img loading="eager" title="黑岩戰弓" src="EquipIcon/UI_EquipIcon_Bow_Blackrock.png" alt="黑岩戰弓" style="background-color:#745a95;">'
                + '<img loading="eager" title="弓藏" src="EquipIcon/UI_EquipIcon_Bow_Recluse.png" alt="弓藏" style="background-color:#745a95;">'
                + '<img loading="eager" title="若水" src="EquipIcon/UI_EquipIcon_Bow_Kirin.png" alt="若水" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="翡玉法球" src="EquipIcon/UI_EquipIcon_Catalyst_Jade.png" alt="翡玉法球" style="background-color:#53799e;">'
                + '<img loading="eager" title="黑岩緋玉" src="EquipIcon/UI_EquipIcon_Catalyst_Blackrock.png" alt="黑岩緋玉" style="background-color:#745a95;">'
                + '<img loading="eager" title="匣裡日月" src="EquipIcon/UI_EquipIcon_Catalyst_Resurrection.png" alt="匣裡日月" style="background-color:#745a95;">'
                + '<img loading="eager" title="遺祀玉瓏" src="EquipIcon/UI_EquipIcon_Catalyst_Yue.png" alt="遺祀玉瓏" style="background-color:#745a95;">'
                + '<img loading="eager" title="碧落之瓏" src="EquipIcon/UI_EquipIcon_Catalyst_Morax.png" alt="碧落之瓏" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="白影劍" src="EquipIcon/UI_EquipIcon_Claymore_Exotic.png" alt="白影劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="千岩古劍" src="EquipIcon/UI_EquipIcon_Claymore_Lapis.png" alt="千岩古劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="白纓槍" src="EquipIcon/UI_EquipIcon_Pole_Ruby.png" alt="白纓槍" style="background-color:#53799e;">'
                + '<img loading="eager" title="流月針" src="EquipIcon/UI_EquipIcon_Pole_Exotic.png" alt="流月針" style="background-color:#745a95;">'
                + '<img loading="eager" title="和璞鳶" src="EquipIcon/UI_EquipIcon_Pole_Morax.png" alt="和璞鳶" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="暗鐵劍" src="EquipIcon/UI_EquipIcon_Sword_Darker.png" alt="暗鐵劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="黑岩長劍" src="EquipIcon/UI_EquipIcon_Sword_Blackrock.png" alt="黑岩長劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="匣裡龍吟" src="EquipIcon/UI_EquipIcon_Sword_Rockkiller.png" alt="匣裡龍吟" style="background-color:#745a95;">'
                + '<img loading="eager" title="斫峰之刃" src="EquipIcon/UI_EquipIcon_Sword_Kunwu.png" alt="斫峰之刃" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Transience.png" alt="Inazuma Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">堇色之庭(稻妻)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="鹿野院平藏" src="AvatarIcon/UI_AvatarIcon_Heizo.png" alt="鹿野院平藏" style="background-color:#745a95;">'
                + '<img loading="eager" title="珊瑚宮心海" src="AvatarIcon/UI_AvatarIcon_Kokomi.png" alt="珊瑚宮心海" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="綺良良" src="AvatarIcon/UI_AvatarIcon_Momoka.png" alt="綺良良" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(雷)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(雷)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(雷)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(雷)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="托馬" src="AvatarIcon/UI_AvatarIcon_Tohma.png" alt="托馬" style="background-color:#745a95;">'
                + '<img loading="eager" title="宵宮" src="AvatarIcon/UI_AvatarIcon_Yoimiya.png" alt="宵宮" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/inazuma_mon4.png" alt="Inazuma Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">砂流之庭(稻妻)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="白辰之環" src="EquipIcon/UI_EquipIcon_Catalyst_Bakufu.png" alt="白辰之環" style="background-color:#745a95;">'
                + '<img loading="eager" title="證誓之明瞳" src="EquipIcon/UI_EquipIcon_Catalyst_Jyanome.png" alt="證誓之明瞳" style="background-color:#745a95;">'
                + '<img loading="eager" title="不滅月華" src="EquipIcon/UI_EquipIcon_Catalyst_Kaleido.png" alt="不滅月華" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="惡王丸" src="EquipIcon/UI_EquipIcon_Claymore_Maria.png" alt="惡王丸" style="background-color:#745a95;">'
                + '<img loading="eager" title="天目影打刀" src="EquipIcon/UI_EquipIcon_Sword_Bakufu.png" alt="天目影打刀" style="background-color:#745a95;">'
                + '<img loading="eager" title="霧切之回光" src="EquipIcon/UI_EquipIcon_Sword_Narukami.png" alt="霧切之回光" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Admonition.png" alt="Sumeru Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">昏識塔(須彌)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="坎蒂絲" src="AvatarIcon/UI_AvatarIcon_Candace.png" alt="坎蒂絲" style="background-color:#745a95;">'
                + '<img loading="eager" title="賽諾" src="AvatarIcon/UI_AvatarIcon_Cyno.png" alt="賽諾" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="琺露珊" src="AvatarIcon/UI_AvatarIcon_Faruzan.png" alt="琺露珊" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(草)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(草)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(草)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(草)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="提納里" src="AvatarIcon/UI_AvatarIcon_Tighnari.png" alt="提納里" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/sumeru_mon4.png" alt="Sumeru Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">有頂塔(須彌)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="䴉穿之喙" src="EquipIcon/UI_EquipIcon_Bow_Ibis.png" alt="䴉穿之喙" style="background-color:#745a95;">'
                + '<img loading="eager" title="森林王器" src="EquipIcon/UI_EquipIcon_Claymore_Arakalari.png" alt="森林王器" style="background-color:#745a95;">'
                + '<img loading="eager" title="原木刀" src="EquipIcon/UI_EquipIcon_Sword_Arakalari.png" alt="原木刀" style="background-color:#745a95;">'
                + '<img loading="eager" title="西福斯的月光" src="EquipIcon/UI_EquipIcon_Sword_Pleroma.png" alt="西福斯的月光" style="background-color:#745a95;">'
                + '<img loading="eager" title="裁葉萃光" src="EquipIcon/UI_EquipIcon_Sword_Ayus.png" alt="裁葉萃光" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="聖顯之鑰" src="EquipIcon/UI_EquipIcon_Sword_Deshret.png" alt="聖顯之鑰" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Equity.png" alt="Fontaine Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">蒼白的遺榮(楓丹)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="林尼" src="AvatarIcon/UI_AvatarIcon_Liney.png" alt="林尼" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="那維萊特" src="AvatarIcon/UI_AvatarIcon_Neuvillette.png" alt="那維萊特" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/fontaine_mon4.png" alt="Fontaine Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">深潮的餘響(楓丹)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="測距規" src="EquipIcon/UI_EquipIcon_Bow_Mechanic.png" alt="測距規" style="background-color:#745a95;">'
                + '<img loading="eager" title="靜謐之曲" src="EquipIcon/UI_EquipIcon_Bow_Vorpal.png" alt="靜謐之曲" style="background-color:#745a95;">'
                + '<img loading="eager" title="最初的大魔術" src="EquipIcon/UI_EquipIcon_Bow_Pledge.png" alt="最初的大魔術" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="勘探鑽機" src="EquipIcon/UI_EquipIcon_Pole_Mechanic.png" alt="勘探鑽機" style="background-color:#745a95;">'
                + '<img loading="eager" title="灰河渡手" src="EquipIcon/UI_EquipIcon_Sword_Machination.png" alt="灰河渡手" style="background-color:#745a95;">'
                + '<img loading="eager" title="水仙十字聖劍" src="EquipIcon/UI_EquipIcon_Sword_Purewill.png" alt="水仙十字聖劍" style="background-color:#745a95;"></div>';
            break;
        case '2':
        case '5':
            output = '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Resistance.png" alt="Mondstadt Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">忘卻之峽(蒙德)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="班尼特" src="AvatarIcon/UI_AvatarIcon_Bennett.png" alt="班尼特" style="background-color:#745a95;">'
                + '<img loading="eager" title="迪盧克" src="AvatarIcon/UI_AvatarIcon_Diluc.png" alt="迪盧克" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="優菈" src="AvatarIcon/UI_AvatarIcon_Eula.png" alt="優菈" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="莫娜" src="AvatarIcon/UI_AvatarIcon_Mona.png" alt="莫娜" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="諾艾爾" src="AvatarIcon/UI_AvatarIcon_Noel.png" alt="諾艾爾" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(風)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(風)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(風)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(風)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="琴" src="AvatarIcon/UI_AvatarIcon_Qin.png" alt="琴" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="雷澤" src="AvatarIcon/UI_AvatarIcon_Razor.png" alt="雷澤" style="background-color:#745a95;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/mondstadt_tue4.png" alt="Mondstadt Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">塞西莉亞苗圃(蒙德)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="神射手之誓" src="EquipIcon/UI_EquipIcon_Bow_Arjuna.png" alt="神射手之誓" style="background-color:#53799e;">'
                + '<img loading="eager" title="祭禮弓" src="EquipIcon/UI_EquipIcon_Bow_Fossil.png" alt="祭禮弓" style="background-color:#745a95;">'
                + '<img loading="eager" title="天空之翼" src="EquipIcon/UI_EquipIcon_Bow_Dvalin.png" alt="天空之翼" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="終末嗟嘆之詩" src="EquipIcon/UI_EquipIcon_Bow_Widsith.png" alt="終末嗟嘆之詩" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="討龍英傑譚" src="EquipIcon/UI_EquipIcon_Catalyst_Pulpfic.png" alt="討龍英傑譚" style="background-color:#53799e;">'
                + '<img loading="eager" title="無垠蔚藍之歌" src="EquipIcon/UI_EquipIcon_Catalyst_DandelionPoem.png" alt="無垠蔚藍之歌" style="background-color:#745a95;">'
                + '<img loading="eager" title="嘟嘟可故事集" src="EquipIcon/UI_EquipIcon_Catalyst_Ludiharpastum.png" alt="嘟嘟可故事集" style="background-color:#745a95;">'
                + '<img loading="eager" title="暗巷的酒與詩" src="EquipIcon/UI_EquipIcon_Catalyst_Outlaw.png" alt="暗巷的酒與詩" style="background-color:#745a95;">'
                + '<img loading="eager" title="流浪樂章" src="EquipIcon/UI_EquipIcon_Catalyst_Troupe.png" alt="流浪樂章" style="background-color:#745a95;">'
                + '<img loading="eager" title="天空之卷" src="EquipIcon/UI_EquipIcon_Catalyst_Dvalin.png" alt="天空之卷" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="沐浴龍血的劍" src="EquipIcon/UI_EquipIcon_Claymore_Siegfry.png" alt="沐浴龍血的劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="祭禮大劍" src="EquipIcon/UI_EquipIcon_Claymore_Fossil.png" alt="祭禮大劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="天空之傲" src="EquipIcon/UI_EquipIcon_Claymore_Dvalin.png" alt="天空之傲" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="龍脊長槍" src="EquipIcon/UI_EquipIcon_Pole_Everfrost.png" alt="龍脊長槍" style="background-color:#745a95;">'
                + '<img loading="eager" title="決鬥之槍" src="EquipIcon/UI_EquipIcon_Pole_Gladiator.png" alt="決鬥之槍" style="background-color:#745a95;">'
                + '<img loading="eager" title="風信之鋒" src="EquipIcon/UI_EquipIcon_Pole_Windvane.png" alt="風信之鋒" style="background-color:#745a95;">'
                + '<img loading="eager" title="黎明神劍" src="EquipIcon/UI_EquipIcon_Sword_Dawn.png" alt="黎明神劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="黑劍" src="EquipIcon/UI_EquipIcon_Sword_Bloodstained.png" alt="黑劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="降臨之劍" src="EquipIcon/UI_EquipIcon_Sword_Psalmus.png" alt="降臨之劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="笛劍" src="EquipIcon/UI_EquipIcon_Sword_Troupe.png" alt="笛劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="天空之刃" src="EquipIcon/UI_EquipIcon_Sword_Dvalin.png" alt="天空之刃" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Diligence.png" alt="Liyue Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">太山府(璃月)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="重雲" src="AvatarIcon/UI_AvatarIcon_Chongyun.png" alt="重雲" style="background-color:#745a95;">'
                + '<img loading="eager" title="甘雨" src="AvatarIcon/UI_AvatarIcon_Ganyu.png" alt="甘雨" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="胡桃" src="AvatarIcon/UI_AvatarIcon_Hutao.png" alt="胡桃" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="楓原萬葉" src="AvatarIcon/UI_AvatarIcon_Kazuha.png" alt="楓原萬葉" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="香菱" src="AvatarIcon/UI_AvatarIcon_Xiangling.png" alt="香菱" style="background-color:#745a95;">'
                + '<img loading="eager" title="瑤瑤" src="AvatarIcon/UI_AvatarIcon_Yaoyao.png" alt="瑤瑤" style="background-color:#745a95;">'
                + '<img loading="eager" title="雲堇" src="AvatarIcon/UI_AvatarIcon_Yunjin.png" alt="雲堇" style="background-color:#745a95;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/liyue_tue4.png" alt="Liyue Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">震雷連山密宮(璃月)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="信使" src="EquipIcon/UI_EquipIcon_Bow_Msg.png" alt="信使" style="background-color:#53799e;">'
                + '<img loading="eager" title="試作澹月" src="EquipIcon/UI_EquipIcon_Bow_Proto.png" alt="試作澹月" style="background-color:#745a95;">'
                + '<img loading="eager" title="甲級寶玨" src="EquipIcon/UI_EquipIcon_Catalyst_Phoney.png" alt="甲級寶玨" style="background-color:#53799e;">'
                + '<img loading="eager" title="試作金珀" src="EquipIcon/UI_EquipIcon_Catalyst_Proto.png" alt="試作金珀" style="background-color:#745a95;">'
                + '<img loading="eager" title="昭心" src="EquipIcon/UI_EquipIcon_Catalyst_Truelens.png" alt="昭心" style="background-color:#745a95;">'
                + '<img loading="eager" title="以理服人" src="EquipIcon/UI_EquipIcon_Claymore_Reasoning.png" alt="以理服人" style="background-color:#53799e;">'
                + '<img loading="eager" title="黑岩斬刀" src="EquipIcon/UI_EquipIcon_Claymore_Blackrock.png" alt="黑岩斬刀" style="background-color:#745a95;">'
                + '<img loading="eager" title="雨裁" src="EquipIcon/UI_EquipIcon_Claymore_Perdue.png" alt="雨裁" style="background-color:#745a95;">'
                + '<img loading="eager" title="無工之劍" src="EquipIcon/UI_EquipIcon_Claymore_Kunwu.png" alt="無工之劍" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="鉞矛" src="EquipIcon/UI_EquipIcon_Pole_Halberd.png" alt="鉞矛" style="background-color:#53799e;">'
                + '<img loading="eager" title="黑岩刺槍" src="EquipIcon/UI_EquipIcon_Pole_Blackrock.png" alt="黑岩刺槍" style="background-color:#745a95;">'
                + '<img loading="eager" title="匣裡滅辰" src="EquipIcon/UI_EquipIcon_Pole_Stardust.png" alt="匣裡滅辰" style="background-color:#745a95;">'
                + '<img loading="eager" title="宗室獵槍" src="EquipIcon/UI_EquipIcon_Pole_Theocrat.png" alt="宗室獵槍" style="background-color:#745a95;">'
                + '<img loading="eager" title="息災" src="EquipIcon/UI_EquipIcon_Pole_Santika.png" alt="息災" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="吃虎魚刀" src="EquipIcon/UI_EquipIcon_Sword_Sashimi.png" alt="吃虎魚刀" style="background-color:#53799e;">'
                + '<img loading="eager" title="試作斬岩" src="EquipIcon/UI_EquipIcon_Sword_Proto.png" alt="試作斬岩" style="background-color:#745a95;">'
                + '<img loading="eager" title="磐岩結綠" src="EquipIcon/UI_EquipIcon_Sword_Morax.png" alt="磐岩結綠" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Elegance.png" alt="Inazuma Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">堇色之庭(稻妻)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="神里綾華" src="AvatarIcon/UI_AvatarIcon_Ayaka.png" alt="神里綾華" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="神里綾人" src="AvatarIcon/UI_AvatarIcon_Ayato.png" alt="神里綾人" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="荒瀧一斗" src="AvatarIcon/UI_AvatarIcon_Itto.png" alt="荒瀧一斗" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(雷)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(雷)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(雷)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(雷)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="九條裟羅" src="AvatarIcon/UI_AvatarIcon_Sara.png" alt="九條裟羅" style="background-color:#745a95;">'
                + '<img loading="eager" title="久岐忍" src="AvatarIcon/UI_AvatarIcon_Shinobu.png" alt="久岐忍" style="background-color:#745a95;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/inazuma_tue4.png" alt="Inazuma Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">砂流之庭(稻妻)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="破魔之弓" src="EquipIcon/UI_EquipIcon_Bow_Bakufu.png" alt="破魔之弓" style="background-color:#745a95;">'
                + '<img loading="eager" title="曚雲之月" src="EquipIcon/UI_EquipIcon_Bow_Maria.png" alt="曚雲之月" style="background-color:#745a95;">'
                + '<img loading="eager" title="掠食者" src="EquipIcon/UI_EquipIcon_Bow_Predator.png" alt="掠食者" style="background-color:#745a95;">'
                + '<img loading="eager" title="飛雷之弦振" src="EquipIcon/UI_EquipIcon_Bow_Narukami.png" alt="飛雷之弦振" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="桂木斬長正" src="EquipIcon/UI_EquipIcon_Claymore_Bakufu.png" alt="桂木斬長正" style="background-color:#745a95;">'
                + '<img loading="eager" title="赤角石潰杵" src="EquipIcon/UI_EquipIcon_Claymore_Itadorimaru.png" alt="赤角石潰杵" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="東花坊時雨" src="EquipIcon/UI_EquipIcon_Sword_Kasabouzu.png" alt="東花坊時雨" style="background-color:#745a95;">'
                + '<img loading="eager" title="波亂月白經津" src="EquipIcon/UI_EquipIcon_Sword_Amenoma.png" alt="波亂月白經津" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Ingenuity.png" alt="Sumeru Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">昏識塔(須彌)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="艾爾海森" src="AvatarIcon/UI_AvatarIcon_Alhatham.png" alt="艾爾海森" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="多莉" src="AvatarIcon/UI_AvatarIcon_Dori.png" alt="多莉" style="background-color:#745a95;">'
                + '<img loading="eager" title="卡維" src="AvatarIcon/UI_AvatarIcon_Kaveh.png" alt="卡維" style="background-color:#745a95;">'
                + '<img loading="eager" title="萊依拉" src="AvatarIcon/UI_AvatarIcon_Layla.png" alt="萊依拉" style="background-color:#745a95;">'
                + '<img loading="eager" title="納西妲" src="AvatarIcon/UI_AvatarIcon_Nahida.png" alt="納西妲" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(草)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(草)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(草)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(草)" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/sumeru_tue4.png" alt="Sumeru Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">有頂塔(須彌)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="盈滿之實" src="EquipIcon/UI_EquipIcon_Catalyst_Arakalari.png" alt="盈滿之實" style="background-color:#745a95;">'
                + '<img loading="eager" title="流浪的晚星" src="EquipIcon/UI_EquipIcon_Catalyst_Pleroma.png" alt="流浪的晚星" style="background-color:#745a95;">'
                + '<img loading="eager" title="千夜浮夢" src="EquipIcon/UI_EquipIcon_Catalyst_Ayus.png" alt="千夜浮夢" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="聊聊棒" src="EquipIcon/UI_EquipIcon_Claymore_BeastTamer.png" alt="聊聊棒" style="background-color:#745a95;">'
                + '<img loading="eager" title="貫月矢" src="EquipIcon/UI_EquipIcon_Pole_Arakalari.png" alt="貫月矢" style="background-color:#745a95;">'
                + '<img loading="eager" title="赤沙之杖" src="EquipIcon/UI_EquipIcon_Pole_Deshret.png" alt="赤沙之杖" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Justice.png" alt="Fontaine Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">蒼白的遺榮(楓丹)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="夏洛蒂" src="AvatarIcon/UI_AvatarIcon_Charlotte.png" alt="夏洛蒂" style="background-color:#745a95;">'
                + '<img loading="eager" title="菲米尼" src="AvatarIcon/UI_AvatarIcon_Freminet.png" alt="菲米尼" style="background-color:#745a95;">'
                + '<img loading="eager" title="芙寧娜" src="AvatarIcon/UI_AvatarIcon_Furina.png" alt="芙寧娜" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(水)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(水)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(水)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(水)" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/fontaine_tue4.png" alt="Fontaine Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">深潮的餘響(楓丹)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="純水流華" src="EquipIcon/UI_EquipIcon_Catalyst_Vorpal.png" alt="純水流華" style="background-color:#745a95;">'
                + '<img loading="eager" title="萬世流湧大典" src="EquipIcon/UI_EquipIcon_Catalyst_Iudex.png" alt="萬世流湧大典" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="船塢長劍" src="EquipIcon/UI_EquipIcon_Sword_Mechanic.png" alt="船塢長劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="海淵終曲" src="EquipIcon/UI_EquipIcon_Sword_Vorpal.png" alt="海淵終曲" style="background-color:#745a95;">'
                + '<img loading="eager" title="靜水流湧之輝" src="EquipIcon/UI_EquipIcon_Sword_Regalis.png" alt="靜水流湧之輝" style="background-color:#af6f2a;"></div>';
            break;
        case '3':
        case '6':
            output = '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Ballad.png" alt="Mondstadt Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">忘卻之峽(蒙德)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="阿貝多" src="AvatarIcon/UI_AvatarIcon_Albedo.png" alt="阿貝多" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="菲謝爾" src="AvatarIcon/UI_AvatarIcon_Fischl.png" alt="菲謝爾" style="background-color:#745a95;">'
                + '<img loading="eager" title="凱亞" src="AvatarIcon/UI_AvatarIcon_Kaeya.png" alt="凱亞" style="background-color:#745a95;">'
                + '<img loading="eager" title="麗莎" src="AvatarIcon/UI_AvatarIcon_Lisa.png" alt="麗莎" style="background-color:#745a95;">'
                + '<img loading="eager" title="米卡" src="AvatarIcon/UI_AvatarIcon_Mika.png" alt="米卡" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(風)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(風)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(風)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(風)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="蘿莎莉亞" src="AvatarIcon/UI_AvatarIcon_Rosaria.png" alt="蘿莎莉亞" style="background-color:#745a95;">'
                + '<img loading="eager" title="溫迪" src="AvatarIcon/UI_AvatarIcon_Venti.png" alt="溫迪" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/mondstadt_wed4.png" alt="Mondstadt Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">塞西莉亞苗圃(蒙德)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="反曲弓" src="EquipIcon/UI_EquipIcon_Bow_Curve.png" alt="反曲弓" style="background-color:#53799e;">'
                + '<img loading="eager" title="風花之頌" src="EquipIcon/UI_EquipIcon_Bow_Fleurfair.png" alt="風花之頌" style="background-color:#745a95;">'
                + '<img loading="eager" title="暗巷獵手" src="EquipIcon/UI_EquipIcon_Bow_Outlaw.png" alt="暗巷獵手" style="background-color:#745a95;">'
                + '<img loading="eager" title="宗室長弓" src="EquipIcon/UI_EquipIcon_Bow_Theocrat.png" alt="宗室長弓" style="background-color:#745a95;">'
                + '<img loading="eager" title="西風獵弓" src="EquipIcon/UI_EquipIcon_Bow_Zephyrus.png" alt="西風獵弓" style="background-color:#745a95;">'
                + '<img loading="eager" title="阿莫斯之弓" src="EquipIcon/UI_EquipIcon_Bow_Amos.png" alt="阿莫斯之弓" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="異世界行記" src="EquipIcon/UI_EquipIcon_Catalyst_Lightnov.png" alt="異世界行記" style="background-color:#53799e;">'
                + '<img loading="eager" title="忍冬之果" src="EquipIcon/UI_EquipIcon_Catalyst_Everfrost.png" alt="忍冬之果" style="background-color:#745a95;">'
                + '<img loading="eager" title="祭禮殘章" src="EquipIcon/UI_EquipIcon_Catalyst_Fossil.png" alt="祭禮殘章" style="background-color:#745a95;">'
                + '<img loading="eager" title="四風原典" src="EquipIcon/UI_EquipIcon_Catalyst_Fourwinds.png" alt="四風原典" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="白鐵大劍" src="EquipIcon/UI_EquipIcon_Claymore_Tin.png" alt="白鐵大劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="飾鐵之花" src="EquipIcon/UI_EquipIcon_Claymore_Fleurfair.png" alt="飾鐵之花" style="background-color:#745a95;">'
                + '<img loading="eager" title="宗室大劍" src="EquipIcon/UI_EquipIcon_Claymore_Theocrat.png" alt="宗室大劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="西風大劍" src="EquipIcon/UI_EquipIcon_Claymore_Zephyrus.png" alt="西風大劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="狼的末路" src="EquipIcon/UI_EquipIcon_Claymore_Wolfmound.png" alt="狼的末路" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="西風長槍" src="EquipIcon/UI_EquipIcon_Pole_Zephyrus.png" alt="西風長槍" style="background-color:#745a95;">'
                + '<img loading="eager" title="天空之脊" src="EquipIcon/UI_EquipIcon_Pole_Dvalin.png" alt="天空之脊" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="旅行劍" src="EquipIcon/UI_EquipIcon_Sword_Traveler.png" alt="旅行劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="祭禮劍" src="EquipIcon/UI_EquipIcon_Sword_Fossil.png" alt="祭禮劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="腐殖之劍" src="EquipIcon/UI_EquipIcon_Sword_Magnum.png" alt="腐殖之劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="蒼古自由之誓" src="EquipIcon/UI_EquipIcon_Sword_Widsith.png" alt="蒼古自由之誓" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Gold.png" alt="Liyue Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">太山府(璃月)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="白朮" src="AvatarIcon/UI_AvatarIcon_Baizhuer.png" alt="白朮" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="北斗" src="AvatarIcon/UI_AvatarIcon_Beidou.png" alt="北斗" style="background-color:#745a95;">'
                + '<img loading="eager" title="煙緋" src="AvatarIcon/UI_AvatarIcon_Feiyan.png" alt="煙緋" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(岩)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(岩)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="行秋" src="AvatarIcon/UI_AvatarIcon_Xingqiu.png" alt="行秋" style="background-color:#745a95;">'
                + '<img loading="eager" title="辛焱" src="AvatarIcon/UI_AvatarIcon_Xinyan.png" alt="辛焱" style="background-color:#745a95;">'
                + '<img loading="eager" title="鍾離" src="AvatarIcon/UI_AvatarIcon_Zhongli.png" alt="鍾離" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/liyue_wed4.png" alt="Liyue Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">震雷連山密宮(璃月)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="鋼輪弓" src="EquipIcon/UI_EquipIcon_Bow_Exotic.png" alt="鋼輪弓" style="background-color:#745a95;">'
                + '<img loading="eager" title="落霞" src="EquipIcon/UI_EquipIcon_Bow_Fallensun.png" alt="落霞" style="background-color:#745a95;">'
                + '<img loading="eager" title="萬國諸海圖譜" src="EquipIcon/UI_EquipIcon_Catalyst_Exotic.png" alt="萬國諸海圖譜" style="background-color:#745a95;">'
                + '<img loading="eager" title="塵世之鎖" src="EquipIcon/UI_EquipIcon_Catalyst_Kunwu.png" alt="塵世之鎖" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="飛天大御劍" src="EquipIcon/UI_EquipIcon_Claymore_Mitsurugi.png" alt="飛天大御劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="螭骨劍" src="EquipIcon/UI_EquipIcon_Claymore_Kione.png" alt="螭骨劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="銜珠海皇" src="EquipIcon/UI_EquipIcon_Claymore_MillenniaTuna.png" alt="銜珠海皇" style="background-color:#745a95;">'
                + '<img loading="eager" title="試作古華" src="EquipIcon/UI_EquipIcon_Claymore_Proto.png" alt="試作古華" style="background-color:#745a95;">'
                + '<img loading="eager" title="黑纓槍" src="EquipIcon/UI_EquipIcon_Pole_Noire.png" alt="黑纓槍" style="background-color:#53799e;">'
                + '<img loading="eager" title="試作星鐮" src="EquipIcon/UI_EquipIcon_Pole_Proto.png" alt="試作星鐮" style="background-color:#745a95;">'
                + '<img loading="eager" title="千岩長槍" src="EquipIcon/UI_EquipIcon_Pole_Lapis.png" alt="千岩長槍" style="background-color:#745a95;">'
                + '<img loading="eager" title="護摩之杖" src="EquipIcon/UI_EquipIcon_Pole_Homa.png" alt="護摩之杖" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="貫虹之槊" src="EquipIcon/UI_EquipIcon_Pole_Kunwu.png" alt="貫虹之槊" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="飛天御劍" src="EquipIcon/UI_EquipIcon_Sword_Mitsurugi.png" alt="飛天御劍" style="background-color:#53799e;">'
                + '<img loading="eager" title="鐵蜂刺" src="EquipIcon/UI_EquipIcon_Sword_Exotic.png" alt="鐵蜂刺" style="background-color:#745a95;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Light.png" alt="Inazuma Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">堇色之庭(稻妻)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="五郎" src="AvatarIcon/UI_AvatarIcon_Gorou.png" alt="五郎" style="background-color:#745a95;">'
                + '<img loading="eager" title="男旅行者(雷)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(雷)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(雷)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(雷)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="早柚" src="AvatarIcon/UI_AvatarIcon_Sayu.png" alt="早柚" style="background-color:#745a95;">'
                + '<img loading="eager" title="雷電將軍" src="AvatarIcon/UI_AvatarIcon_Shougun.png" alt="雷電將軍" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="八重神子" src="AvatarIcon/UI_AvatarIcon_Yae.png" alt="八重神子" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/inazuma_wed4.png" alt="Inazuma Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">砂流之庭(稻妻)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="冬極白星" src="EquipIcon/UI_EquipIcon_Bow_Worldbane.png" alt="冬極白星" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="神樂之真意" src="EquipIcon/UI_EquipIcon_Catalyst_Narukami.png" alt="神樂之真意" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="喜多院十文字" src="EquipIcon/UI_EquipIcon_Pole_Bakufu.png" alt="喜多院十文字" style="background-color:#745a95;">'
                + '<img loading="eager" title="斷浪長鰭" src="EquipIcon/UI_EquipIcon_Pole_Maria.png" alt="斷浪長鰭" style="background-color:#745a95;">'
                + '<img loading="eager" title="漁獲" src="EquipIcon/UI_EquipIcon_Pole_Mori.png" alt="漁獲" style="background-color:#745a95;">'
                + '<img loading="eager" title="薙草之稻光" src="EquipIcon/UI_EquipIcon_Pole_Narukami.png" alt="薙草之稻光" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="籠釣瓶一心" src="EquipIcon/UI_EquipIcon_Sword_Youtou.png" alt="籠釣瓶一心" style="background-color:#745a95;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Praxis.png" alt="Sumeru Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">昏識塔(須彌)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="柯萊" src="AvatarIcon/UI_AvatarIcon_Collei.png" alt="柯萊" style="background-color:#745a95;">'
                + '<img loading="eager" title="迪希雅" src="AvatarIcon/UI_AvatarIcon_Dehya.png" alt="迪希雅" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="妮露" src="AvatarIcon/UI_AvatarIcon_Nilou.png" alt="妮露" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="男旅行者(草)" src="AvatarIcon/UI_AvatarIcon_PlayerBoy.png" alt="男旅行者(草)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="女旅行者(草)" src="AvatarIcon/UI_AvatarIcon_PlayerGirl.png" alt="女旅行者(草)" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="流浪者" src="AvatarIcon/UI_AvatarIcon_Wanderer.png" alt="流浪者" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/sumeru_wed4.png" alt="Sumeru Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">有頂塔(須彌)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="王下近侍" src="EquipIcon/UI_EquipIcon_Bow_Arakalari.png" alt="王下近侍" style="background-color:#745a95;">'
                + '<img loading="eager" title="竭澤" src="EquipIcon/UI_EquipIcon_Bow_Fin.png" alt="竭澤" style="background-color:#745a95;">'
                + '<img loading="eager" title="烈陽之嗣" src="EquipIcon/UI_EquipIcon_Bow_Gurabad.png" alt="烈陽之嗣" style="background-color:#745a95;">'
                + '<img loading="eager" title="獵人之徑" src="EquipIcon/UI_EquipIcon_Bow_Ayus.png" alt="獵人之徑" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="圖萊杜拉的回憶" src="EquipIcon/UI_EquipIcon_Catalyst_Alaya.png" alt="圖萊杜拉的回憶" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="瑪海菈的水色" src="EquipIcon/UI_EquipIcon_Claymore_Pleroma.png" alt="瑪海菈的水色" style="background-color:#745a95;">'
                + '<img loading="eager" title="葦海信標" src="EquipIcon/UI_EquipIcon_Claymore_Deshret.png" alt="葦海信標" style="background-color:#af6f2a;"></div>'
                + '<div class="talentTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="Talent/Philosophies of Order.png" alt="Fontaine Talent Domain">'
                + '<div style="font-weight: thin; font-size: large;">蒼白的遺榮(楓丹)</div></div>'
                + '<div class="characters" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="琳妮特" src="AvatarIcon/UI_AvatarIcon_Linette.png" alt="琳妮特" style="background-color:#745a95;">'
                + '<img loading="eager" title="萊歐斯利" src="AvatarIcon/UI_AvatarIcon_Wriothesley.png" alt="萊歐斯利" style="background-color:#af6f2a;"></div>'
                + '<div class="weaponTitle" style="display: flex; align-items: center;">'
                + '<img loading="eager" src="weapon/fontaine_wed4.png" alt="Fontaine Weapon Domain">'
                + '<div style="font-weight: thin; font-size: large;">深潮的餘響(楓丹)</div></div>'
                + '<div class="weapons" style="display: flex; flex-wrap: wrap;">'
                + '<img loading="eager" title="金流監督" src="EquipIcon/UI_EquipIcon_Catalyst_Wheatley.png" alt="金流監督" style="background-color:#af6f2a;">'
                + '<img loading="eager" title="便攜動力鋸" src="EquipIcon/UI_EquipIcon_Claymore_Mechanic.png" alt="便攜動力鋸" style="background-color:#745a95;">'
                + '<img loading="eager" title="浪影闊劍" src="EquipIcon/UI_EquipIcon_Claymore_Vorpal.png" alt="浪影闊劍" style="background-color:#745a95;">'
                + '<img loading="eager" title="峽灣長歌" src="EquipIcon/UI_EquipIcon_Pole_Shanty.png" alt="峽灣長歌" style="background-color:#745a95;">'
                + '<img loading="eager" title="公義的酬報" src="EquipIcon/UI_EquipIcon_Claymore_Vorpal.png" alt="公義的酬報" style="background-color:#745a95;"></div>';
            break;
    }
    document.getElementById("display").innerHTML = output;
}

function start() {
    const today = new Date().getDay();
    const selectday = document.getElementById("day")
    selectday.value = today.toString();
    selectChange();
    selectday.addEventListener("change", selectChange, false);
}
window.addEventListener("load", start, false);
